name: static webpages deployment to github pages

on:
  push:
    branches: [  "main"  ]
    paths:   
      - 'index.html'
      - '.github/workflows/**'

permissions:
     contents: read
     pages: write
     id-token: write



jobs:
   build and deploy:
      runs-on: ubuntu-latest 
      steps:
      
        - name: checkout repository
        - uses: actions/checkout@v4
        
        

        - name: Set up GitHub Pages
          uses: actions/configure-pages@v5

        - name: upload static web page
          uses: actions/upload-pages-artifact@v3
          with:
            path: '.'

        - name: Deploy to github Pages
          uses: actions/deploy-pages@v4            
      

